[2024-07-19T10:52:34.431+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: count_accidents.park_count_number_of_accidents manual__2024-07-19T10:52:31.633802+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
